version: "3"
services:
  customer-db:
    image: postgres
    container_name: customer-db 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./docker_volume/postgres_db:/var/lib/postgresql/data
    