version: "3"
services:
  customer-db:
    platform: linux/amd64
    image: postgres
    container_name: customer-db 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./docker_volume/postgres_db:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  
  flask-app:
    platform: linux/amd64
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./api:/app/api